# Generated by Django 2.0 on 2019-06-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_filer_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerimage',
            name='style',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('image-holder', 'Image holder')], default='', max_length=50, verbose_name='Style'),
        ),
    ]
