# Generated by Django 2.0 on 2019-06-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_filer_image', '0002_auto_20190612_1659'),
        ('cmsplugin_filer_image', '0009_auto_20160713_1853'),
    ]

    operations = [
    ]
